name: Upload Library

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-upload:
    if: github.repository == 'instinkt900/canyon'
    runs-on: ${{ matrix.os == 'windows' && 'windows-latest' || 'ubuntu-latest' }}
    strategy:
      matrix:
        os: [windows, linux]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Add private artifactory
      run: |
        conan remote add artifactory https://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}

    - name: Build package and upload
      run: |
        conan create . --profile conan/profiles/${{ matrix.os }}_profile --build=missing -s build_type=${{ matrix.build_type }}
        conan upload canyon --confirm --remote artifactory
