name: Upload Library

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-and-upload:
    if: github.repository == 'instinkt900/canyon'
    runs-on: ${{ matrix.runs_on }}
    strategy:
      matrix:
        os: [windows, linux]
        library_type: [shared, static]
        include:
          - os: windows
            runs_on: windows-latest
          - os: linux
            runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Conan
      uses: conan-io/setup-conan@v1
      with:
        cache_packages: true

    - name: Add private artifactory
      run: |
        conan remote add artifactory https://artifactory.matthewcotton.net/artifactory/api/conan/conan-local
        conan remote login artifactory ci -p ${{ secrets.ARTIFACTS_TOKEN }}

    - name: Build package and upload
      run: |
        conan create . --profile conan/profiles/${{ matrix.os }}_profile --build=missing -o canyon/*:shared=${{ matrix.library_type == 'shared' && 'True' || 'False' }}
        conan upload canyon --confirm --remote artifactory
